[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "f2987c3a1ab356c43faf29b7553d12607412099f"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "35f737f384f82de21b5b13ea389c752e1f6b8f9c85a166be90e593223f8989aa"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.aarch64-apple-darwin.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "e2fd2ce9906e7078cad7429e8dcfad944236d13d"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "2dd01abd70547954d47055a6fca7bc24a807255e229c1d2b18abb082e6f60d2f"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.aarch64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "f16920e2789171b3ff0f70c7ae4ad4a85a4018d2"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "60821f16e3d2b5fb4d66ebb217591a0e61ed84c5fb082bdc0dc31cb3b2fa471b"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.aarch64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "a08a499874e5ce326912449631ef77fd866f8643"
os = "freebsd"

    [[FFMPEG.download]]
    sha256 = "532cbeb569f121381df4cbbc59efef357c6d8141a197be590155ddd364544e9e"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.aarch64-unknown-freebsd.tar.gz"
[[FFMPEG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "da0d43b34d139bb59222f9bdb5e202b679bb360d"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "b25ae70ea5301ed3368b580e9e2f94ec0430ab5900e06df9334561268ec175c2"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.armv6l-linux-gnueabihf.tar.gz"
[[FFMPEG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "910641eb80c57bbe173005bbe55a6b24cd2e77f5"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "ba8a834b9f24b644ed4f2cc4a8249d30d213a9fbc371f26344aff40a82101af7"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.armv6l-linux-musleabihf.tar.gz"
[[FFMPEG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "03bf4703201ce51e2d84fd2088a06d7f5d782c1d"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "fb833934b624f0cb8332d98943f6cc4e5892c22b26ae025db22a5ecbddf57ac7"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.armv7l-linux-gnueabihf.tar.gz"
[[FFMPEG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d9f06ba102ef35103a655e96b87dcb34e4279a9e"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "9ec1fd02eddf5e6bc907c6646ed8dec2dff9ba120b7e6ca2a32f7a7eb29115e3"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.armv7l-linux-musleabihf.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "c52d636c3b38d39ea1ac83df7870fe248745f3f0"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "e66765cd8280bf40f62151ae761f179fff38a2b25e7b38900525f40fe20fd47e"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.i686-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "cc9312084a602a9d0ba8ddfb470a4d490f99af75"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "8f41ad544730acd1c432ec70573d5c2482a8142862da7e9072e2bd319b436d88"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.i686-linux-musl.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "17510ff0fdd9dbdea3a3fa2208708721439e1a3d"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "d8a00472d58093c31f38c8e12a2a611bad2b91a4fe560249a16ae6e598b2ab8a"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.i686-w64-mingw32.tar.gz"
[[FFMPEG]]
arch = "powerpc64le"
git-tree-sha1 = "e77da276c8791fae2af3d7ca83453440e23e34b6"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "e799c2a6ada72213d414018979323d9de52c15b5483cfad941b523a890d3eaeb"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.powerpc64le-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "riscv64"
git-tree-sha1 = "9c85d58a5e0acd5346ed429ccfab04f9ea41dbfc"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "4392950eb667524c4608cdd92346f5f1c02191e5e4aa24c04214154c63327feb"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.riscv64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "2f8357dc577304f5e4f4af2c3a3874fa8a0735e6"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "90eacd61b04f1f4394b102b50a2572332d700fbda66fcf21f3adecdff0e8700e"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.x86_64-apple-darwin.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "2b2f7c502ec3d6f64ee8fe03c85171a8c469b56a"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "030fae10415359b5d2bba21610c6d3796f21f2043cdb8dbfd8230efde204265b"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.x86_64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "8d8fdaa09a14bcaa385e7d4d5a6b9a592324a39e"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "2e947d0c1c6fab29f7d2a15620d4fe6561341a608d6c02246df88dd722a770f1"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.x86_64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "249522a9b1b6a1a64e9b35ad6a6d4b5dd17e81bf"
os = "freebsd"

    [[FFMPEG.download]]
    sha256 = "12a4c016ef0c0dd7f54880a67c856baa49c5e6a9a41ea680ab5a5056651bf0d4"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.x86_64-unknown-freebsd.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "8f71eb37d5b304026b6363d835f8c65ff1920339"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "d919519a20719c0bf6e726e762df86b94425ce58bb37f61953fbf836f6312c27"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.1+0/FFMPEG.v7.1.1.x86_64-w64-mingw32.tar.gz"
