[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "7f02b4185a4a62689cdbaaa60e939d407dd6f11a"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "12e059c3f9578261fe9e850f48dc089dcdd2996636d429f79efb0e55ce730595"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.0+0/FFMPEG.v7.1.0.aarch64-apple-darwin.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "ef41ab0861792e84c6bbc5a52a4128cd9049805e"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "7b8ea4c61ce6b9227376d474a5a5bfe73a1e09d963f369a69b9aacfab4bd4d07"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.0+0/FFMPEG.v7.1.0.aarch64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "3f0ea8440dbb3fcfe0b74ba31b208c1834a6ecdb"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "4e235b856b7a3c1c188dd3c68393ede1c75834647e8e34d4e9f10686b367286f"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.0+0/FFMPEG.v7.1.0.aarch64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f4148de4df2fd238dc0357944112eee3ef4a6b34"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "26f78fcfad0314488fd22653a462b4321f00d7fdc2bae27d9f475b71d100ece6"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.0+0/FFMPEG.v7.1.0.armv7l-linux-gnueabihf.tar.gz"
[[FFMPEG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b8a4c330a1a08991a7dcc2beb8c522f4ba8744c0"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "8fbec5acfb8efd8b62ce6002e55e97e0326a58efb72bbe677119810b795ce9bc"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.0+0/FFMPEG.v7.1.0.armv7l-linux-musleabihf.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "8d5b1b04261c1d6cac8b81669df7d17d36ea535a"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "351aa492ae683b96ce1050344cb4d5467b0e48a364b35ff82bdd83640ca1b229"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.0+0/FFMPEG.v7.1.0.i686-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "79426850c03938af9de46fcadec72a12436bc0d9"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "da6e5a9bc82e1579a6e22f1e741a24932d6d0eedfc224cf1a98b0aea6a0aaf7c"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.0+0/FFMPEG.v7.1.0.i686-linux-musl.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "58d5142959d61a9c5aacad439cd87f58eb748c36"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "14cc896351a54c583ffd086f43e9333b2418618244e383abfcf0b91c4d9c3e98"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.0+0/FFMPEG.v7.1.0.i686-w64-mingw32.tar.gz"
[[FFMPEG]]
arch = "powerpc64le"
git-tree-sha1 = "d22308e18b6ef0cc2faa8ef4f79c9a109571acee"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "f25df6ff60262e4e8f8bdec2bd0d79ccb0a06d15264ac463895b42077709f4ed"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.0+0/FFMPEG.v7.1.0.powerpc64le-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "f637fec116832403f6e634c6b92cf6203c65ea54"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "6a307c774a7200893401a15a5c23cd49261741fb6c8affd2968c81cbc2260d04"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.0+0/FFMPEG.v7.1.0.x86_64-apple-darwin.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "debe72d6fc54b832db8a65abcab85a88ced378d8"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "a925b8597f5f67ea0b6c5fd995b624a55a4f47c41cf1ecae4af4fac0541193f1"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.0+0/FFMPEG.v7.1.0.x86_64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "c3c606c6121cd9e32f002aa14e4fbce9109e7e9a"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "af50a77b08117b5d7c1ad54e6b238cf34b094d04695a5854f7885257453a379e"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.0+0/FFMPEG.v7.1.0.x86_64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "39305e260959eb008621167aa2605a55cc40f6ef"
os = "freebsd"

    [[FFMPEG.download]]
    sha256 = "dfa838a515adc16e28e03ecc8a5821a61793f3fa180ba5b5603bf92476bcbfd6"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.0+0/FFMPEG.v7.1.0.x86_64-unknown-freebsd.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "d4539b50618f2f2f37527faa4afe24ca9b3333cc"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "d7c06af0f14234d15f7c83af9a864a4e43d37a86ce9a6faf17b5feac0f60f030"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v7.1.0+0/FFMPEG.v7.1.0.x86_64-w64-mingw32.tar.gz"
