[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "044f11e5863dced77c678d7d15e3e0bcc60936d9"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "151b47bdab1f007d93ba90d4fa560a40c0b3d6a5854ed6a0ef61003affbe7c48"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.aarch64-apple-darwin.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "7a602f1dc5b0aa3fdbbfaed2cf71706256b61aac"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "cd04efc62c39b2d4bad9161fc2ed94c8a78642955a242f4830d121f5babab556"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.aarch64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "5c83964c378b23b5a271d4409760527e84920f62"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "2554277ba09105be797352304c9b7f4d0b0f8ee8865015262e7fb65622d2f8e1"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.aarch64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "70bff704310c60735bb63d0fdf3cbf231bc9bd31"
os = "freebsd"

    [[FFMPEG.download]]
    sha256 = "3545e04ef6db5f393b19b105c213b001704112952bf019e1eaa8b2c02acf7437"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.aarch64-unknown-freebsd.tar.gz"
[[FFMPEG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9985448cce6e3cf60e181307dbb8c8aaf43c19fb"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "08a51f467d2a860008034e79f0d624c182230aa83242805b1fa9e349fb1e3bfe"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.armv6l-linux-gnueabihf.tar.gz"
[[FFMPEG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "20757fb38a9921d88d5a25a63e7b8f62939477d5"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "eacb96e790c8892dbba118c9f8d058cfb7bbc58accb256f846dc66e19ccd6bb5"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.armv6l-linux-musleabihf.tar.gz"
[[FFMPEG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "66bf0967c442b53be2af7264f59d0c72b53ab2e6"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "482c8ae402634dcea7b54f94c0d471e5df468197e7bbb7cd05bc00a592fabc61"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.armv7l-linux-gnueabihf.tar.gz"
[[FFMPEG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8920b58d96fa3d3efe75b3572c88bd6ccd4bce08"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "4cee4219ecb55a8d2862467901bd0f5dd53a40891f20cc2ef466dd9bb3b5366f"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.armv7l-linux-musleabihf.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "0c2260a70aaeb65b99780fd5f39aa323d52813d1"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "17ef77d9cc5cb824a92101bbf1424a279fcafcd2fdbdbfa2aafe6c83a37f286c"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.i686-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "81ab60cb9939a4d95b1f5bdf88f4265ee5a03a31"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "75cca3a795c26acdad23a832b442faae125680c96d17130ea13f7f56b5889770"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.i686-linux-musl.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "d4b9b19d5aa14c09f6bf9197d91a8c93b25906fc"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "ce2f673dcb4366f4a129a20d18c466c0fb15010e40633787fca1769fe215630c"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.i686-w64-mingw32.tar.gz"
[[FFMPEG]]
arch = "powerpc64le"
git-tree-sha1 = "f06d6e95fcd40347f71c87683bff73f63b79fcab"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "b5e13cb78586369a2a898f60debff2e58e509574e9e48bbb979755311fa6f5dd"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.powerpc64le-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "riscv64"
git-tree-sha1 = "8bb611b48dd3f25de147faa9560af717ba660a21"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "d85c1ca45ce62431064e61b6a75ea2c98289170538e5d94a3df0cdce32d38147"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.riscv64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "e99150e274ab3ed034c810da3f4ba7ef27fc93d2"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "282945fb8ee5ab07172eca3eb4548322e31853a73a08bfff8c981746bad481f8"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.x86_64-apple-darwin.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "0319290fc39dd3bdcb6fb33a4f25d7b8c511c762"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "6361a8b05c19231a1f8f41b6befc6bed081ff36e85a83cd47b11c5c6394da192"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.x86_64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "8884c9f8c6287ee2783ff89ace68158980987c10"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "0630b5a1be907ef7bad6ac4b81b36752612697bb4c7c58b59d246dd3af663fc5"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.x86_64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "ac68a5a55ecbb8c41f5667fd106e032b1aeeaf85"
os = "freebsd"

    [[FFMPEG.download]]
    sha256 = "d7d3714731411057c1622e23ecddf7ce9bf8b43425125c99e196191f64aaaca8"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.x86_64-unknown-freebsd.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "e53c880b3a155c54b452cbe94b72de51158aea2e"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "4854068fab91b60060ec315ba53e024ef2dcb134131014b320666f26a8f797f8"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v6.1.3+0/FFMPEG.v6.1.3.x86_64-w64-mingw32.tar.gz"
