[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "bfd1d8b6b62832cf6a4cb007a832d73b91d6bed9"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "a3ba0ec933590583f541f44053e80098f55e13bc8d77911cdb34701eed510a9d"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.aarch64-apple-darwin.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "f8e1f6e4cd8b13856ef655d91a363e744b4ca291"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "5349dd61985ba4388aec8eff1a5277b49e9e12e6fb0632cb494d61a90d175966"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.aarch64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "fe6314ffdd0fe61c484b0e8a7a50b42eb29f5356"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "19a2001f51b04d78eaf6d8dd849eaedb297db4ee25d09ac4d3a192f976414c32"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.aarch64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "4715294a2f5b6fcb03315d2eb404f8a8e3d978ba"
os = "freebsd"

    [[FFMPEG.download]]
    sha256 = "8a52dfd0f54bbc78b7a6d0ccc4fa6f5623c0124c4a810b1feaa42c2ac9cb434d"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.aarch64-unknown-freebsd.tar.gz"
[[FFMPEG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d3b244bd0bbe6da048bc89d6a60559d5906a16b7"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "bab3ff2c7c143578ae37e26d03f401fd48d6fd677e1eb4e9c059ab907dfac4db"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.armv6l-linux-gnueabihf.tar.gz"
[[FFMPEG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "85cc0b9a1feafc7ff36d6a0974fd349f856e6fc1"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "5909284a179b1847c12489ea9c275987a2af28c1067dd9d2dafd41052a2e8b97"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.armv6l-linux-musleabihf.tar.gz"
[[FFMPEG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f6d491137b9dd699f16e25257b5f0db94f942a86"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "ccb208eb63c0da32356cd67822d53dd6eb0ce772913ba387b0d813a239d48d6a"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.armv7l-linux-gnueabihf.tar.gz"
[[FFMPEG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3728bb57f968591ff51eb6befd92419c506f4f4b"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "093f9e52360f767e93a8fd1de810301ce855915e8dc6e54518b439bf51d610b4"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.armv7l-linux-musleabihf.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "f5a62f825056f6706f622598063b3a62fba480f5"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "a8e8f18f6f2acee75b0a01c3a6558df69e9e551df7bb594352eb39bce945295d"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.i686-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "7facdc5affb62c0a6ff9581216667a49fba3646d"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "81a0312ad4dd1527806e9fc415ed9bdb048826c13e093d2b88620f34ae123a7c"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.i686-linux-musl.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "38cb7dc1bb3836498eda18c2aa971c50ff7aeedd"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "5323571a134aba224c84a93d6a61c3626b0066b0e93480c9d17676cf16f3dfb4"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.i686-w64-mingw32.tar.gz"
[[FFMPEG]]
arch = "powerpc64le"
git-tree-sha1 = "7a1109c07db2042f5cfe35192cee71040a159efa"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "30cd3046529c34a1a1cf1ff983070b78925a01b863c65fbbd7425ed62a1dac60"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.powerpc64le-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "riscv64"
git-tree-sha1 = "52e3689a0f49e44dfd045cd4366252915851caa8"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "35f7dc0d6437e5408c81bdd87c83fa5f901f6b6937bd169cacc5d2e854b05451"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.riscv64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "e6d9dd80db96876d8c9de05bda9374b1fcdae820"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "26302782c5bcc61b2dc9a90ee6785e91495947c980b2d44113091d8abebac8b3"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.x86_64-apple-darwin.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "62487207e82e0829a25b1412f7bdc645bfa1dc46"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "883519330d40e281517ac0eda48937ae02ce99ec079d79faa3dfc5e0838b68c4"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.x86_64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "ff68506e0aa2052f015189a7afa4911d678828b8"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "cfaca0908c4b52fbd015de17c0c36b17ec96cf825f8b90c52bafc776841cb451"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.x86_64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "38fd003464f5733677e0989d7f122ba15f3f9383"
os = "freebsd"

    [[FFMPEG.download]]
    sha256 = "72f4e7b942cb813f76c141483de925aa8f2d8152ae893fed5cf74b15c264c368"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.x86_64-unknown-freebsd.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "f2725b939d748b133719ea8d64ec618668dfc881"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "b492e7e20e2f58f527a6f6cffb33826a453b838c4355cf4b73d3de92167d98ba"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.1.2+0/FFMPEG.v8.1.2.x86_64-w64-mingw32.tar.gz"
