[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "edc52b246257a6a584e140abf9d9658504f99264"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "96bca0b137f89c72ade9d4dc683b0d9cf0ab0dbf59a838922b316096de43bb78"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.4.2+0/FFMPEG.v4.4.2.aarch64-apple-darwin.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "80647a45f3ee3f5b8f96ba2073c102a3d49a989f"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "6bff863d095abfb4993d9d551c0a06321d1899a3814c1e8cfa1ecda60fc692f5"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.4.2+0/FFMPEG.v4.4.2.aarch64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "66290b8ae06576e7284fa8cfb68a27a1620e8bf2"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "3c7a4ff564d2d5a3acdb2cc50241b4604ad9631f05a88f4625f847c1eac1e2e8"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.4.2+0/FFMPEG.v4.4.2.aarch64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2d155f079f257cfcf1a16f01e1d7b2d2fd6637ae"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "6db814560b2e411166e51b74d509cb72b3f56558546224b6baf9615ea53a7448"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.4.2+0/FFMPEG.v4.4.2.armv7l-linux-gnueabihf.tar.gz"
[[FFMPEG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b406bef7a6377ecf1b1c8ccf1f2750a373ef1f8e"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "442dec0ca3fb7a1c1496d33c0475d7ba2bf7d82a29af787859d001a89cadded2"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.4.2+0/FFMPEG.v4.4.2.armv7l-linux-musleabihf.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "8171864473f7701fe673ba78012f3d4eda0b1e8f"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "d1319fcaf22230a9a4d91b260291e54d169568b4081a3b92f0224e9b5a532f9b"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.4.2+0/FFMPEG.v4.4.2.i686-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "3bd907f012842e893cde82f06d69f5b407dfb4be"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "176fd354e6400803ad7abb9481e24def853a62906472a7a7d5f0a2010458a165"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.4.2+0/FFMPEG.v4.4.2.i686-linux-musl.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "a434e6acfade7c2e76b6f42505c2bd8f45c57fd5"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "20dc13357c06cc154aff8bcaa71331dcec10a041b1561ca1ca14181328aefd83"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.4.2+0/FFMPEG.v4.4.2.i686-w64-mingw32.tar.gz"
[[FFMPEG]]
arch = "powerpc64le"
git-tree-sha1 = "3df3de658ca2ba993b38a63fb58cd122a114f216"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "0556c7527ba59aae99fce8e8e3fe232c432afd3f5c779028bbf2b986a7b0c79a"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.4.2+0/FFMPEG.v4.4.2.powerpc64le-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "c759795325eba6523fb1157b582551d4250575e1"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "f7614d735ab527f6504d81c935a051949dc5f322ad449208401b02db5b76d1a2"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.4.2+0/FFMPEG.v4.4.2.x86_64-apple-darwin.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "ba238eaee720c8a6e5d374526a754730c86e823f"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "7e7ee5ed23e864a733290493ed476c08b804a44dd45758f2389132d593512aea"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.4.2+0/FFMPEG.v4.4.2.x86_64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "ae758c19c83e2df21432edb3854a849e2928017a"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "7511280f8bad1300b5d57c12cbf7158728f361c9fee6c5f92d1ce277dea7be86"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.4.2+0/FFMPEG.v4.4.2.x86_64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "68766378a5a587a2612306c750b041c475d1dd90"
os = "freebsd"

    [[FFMPEG.download]]
    sha256 = "4ea883cdf88a80e3a19f769a6f74a2e21459567ab5b6a35522c5faa51427d6df"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.4.2+0/FFMPEG.v4.4.2.x86_64-unknown-freebsd.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "4bb7d8b702e81f58099ea3a710188a616999662b"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "e4269140e54e0ff57a40cbcc8e211ba29903227c22c8229241b7324bb0cbdd4c"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.4.2+0/FFMPEG.v4.4.2.x86_64-w64-mingw32.tar.gz"
