[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "c45dfcd374e6d907119269378fccad36918becaa"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "706c72f757b316fa6c97819e319e24777ea685d45579bd4e907eddf07bc1b226"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.aarch64-apple-darwin.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "557a713688a6d477df7681a175fbb2cd5b2feb27"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "cea5791ca33467693919b98c93a08dd3e2b4b7cafcae33ce7c64cbd249cb1f88"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.aarch64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "4359d12f54ea8c4e6db5afec7abf60089110ddd9"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "71143d38420e7e9fa3d389056e27ba862b074286ae962e749b5eec97835e8973"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.aarch64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "8414631c7873d2f2e3a10abb9995f40a466f773a"
os = "freebsd"

    [[FFMPEG.download]]
    sha256 = "c16a3c15fb33b378acb97d73eee8abf84880ca2ac31a9077d816106b0bcbb861"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.aarch64-unknown-freebsd.tar.gz"
[[FFMPEG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9d0dd3110293c5f8e1d91a1ed6018827d09582a0"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "b0e16ba5cbb0f92de1d2b200f7aa9c46b60c6eb5fd9633a79dc3883d1d2cf653"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.armv6l-linux-gnueabihf.tar.gz"
[[FFMPEG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3c6ab78380bd2f10f9af0384ae8902ac8bef9e58"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "6f8303f1545385f0dfc4fe9d8fea4fe994a2afb093e5e4d58455287ee55bcc76"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.armv6l-linux-musleabihf.tar.gz"
[[FFMPEG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "617e360f28109f8b20622a38cb839a68e6740a9c"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "aa0e03714c49779d2f5bf2180fcb30c3814a09b7dfc53b999bc1b44935e598ab"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.armv7l-linux-gnueabihf.tar.gz"
[[FFMPEG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a44786bca73964b3b4c39d44e6c403888b0437e4"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "42e2f1967ec9eed4f28547ef7ac3763536a793f7c8f51392f319c1c1378176a2"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.armv7l-linux-musleabihf.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "d4c9e416d268e9010b4b9bbced3903a8ddad0ed9"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "4be2658712d5fc4a764ea54d9f69a3421a5aeb26edda8eb5e8234d2bbfa22dce"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.i686-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "bf85531cd034123b92e49c6688743a11714d3211"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "e8e02b8b0b3bb3b9c6b6873692dce839a9d7c09fb051544d277fa91daa1950e9"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.i686-linux-musl.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "f8b34958393219e4f97fccba62531a82b42a9010"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "98f47dbd8640cac8e102fe8ba56e9ff68468087905eb3a7e18078efdd62d4904"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.i686-w64-mingw32.tar.gz"
[[FFMPEG]]
arch = "powerpc64le"
git-tree-sha1 = "22a18cd7cb1d833e039ba2393727c69a2d61f075"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "f24619dd214ad14cedf68863c095d73c88dcced8f3a5cd95fe71a985db19a581"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.powerpc64le-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "riscv64"
git-tree-sha1 = "b0b434fe29675757c3016844143d094fa93f1777"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "cf51dfcca0c88ec71ec36092060f9cb27183a99ff965520b022aec266419abf4"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.riscv64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "d611dacb2c891b85ac0a650b15df5b7c20deeccb"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "9fd048aa8372e99d25838602b8d92d0a2a9a82a93a47bcfcaea5827059d81daa"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.x86_64-apple-darwin.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "54cb5e7e4e2f8043144d964b7c7dddf8d6140b08"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "d82646e93feab264dd566b0dcb37e434de50a918f55b7d944b315e28739a231f"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.x86_64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "89c77718fba06a6c75a1854ca2123654154ea069"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "94d4a49e21d5c3ae2a9b85f16cb589090cc0717aed8e16485ddb4044695df2e8"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.x86_64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "f9aadcdd0df2bcb804202a8f22eb6107d87949d0"
os = "freebsd"

    [[FFMPEG.download]]
    sha256 = "a88127d772fd43c10473836176c0efdc27ec1097d80e9169a62ffc03779db4e2"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.x86_64-unknown-freebsd.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "ae85432cec0a51290aa6cdd83a36966de3d0e4f2"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "2691b86cd87679eedaf5c9485519f6e80cd78fd0d14dd0296863919dd3df3a6b"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.1+1/FFMPEG.v8.0.1.x86_64-w64-mingw32.tar.gz"
