[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "d77a06ae92f018f18ebec90a0d917eaa17e1bca3"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "a8b5a69ca05bcc90397ca4d55f435db22cdc7c733716c78d1bb875b2ff0bcacb"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.3.1+0/FFMPEG.v4.3.1.aarch64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "c4be0e46244e6bd06ee8f6490654a2a7bb83c426"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "f8180b7170b963e783318b74e6116ec7f50cb58dd27a1894c2f49e542c230cc4"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.3.1+0/FFMPEG.v4.3.1.aarch64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "armv7l"
git-tree-sha1 = "ff711a5d9c07c75d956913b59d3cab95581c4829"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "fd2e3cc10a3140068d13b6eb9c4c13c4fd34babf1d4aa5b5481c4a972bee1ad4"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.3.1+0/FFMPEG.v4.3.1.armv7l-linux-gnueabihf.tar.gz"
[[FFMPEG]]
arch = "armv7l"
git-tree-sha1 = "524bf01975c2b689811410e83eb06caa1227c8aa"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "2de93478c5c581de3923df9cbef05cc688bba56506e46a3dce17e3388c705cca"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.3.1+0/FFMPEG.v4.3.1.armv7l-linux-musleabihf.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "7cd3b2d2c8a312165f35f82d84562cb03797776d"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "c457cee740c92e6a435120403b7a440255a020fa52f405957d987ad20e411fb4"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.3.1+0/FFMPEG.v4.3.1.i686-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "33cf432a60d23e5bad4368922d4ec25273119d62"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "6aec33bc33d0cbe998fca5280c4e3ba514676fa8205b1cec504f46054d0a8336"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.3.1+0/FFMPEG.v4.3.1.i686-linux-musl.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "1b162b2a6c3796f10cc02c6081aba64e25997642"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "987b685fb730aaf179ea0614c32b01bd1636fdfa80d000fae2b9f4be0d62a964"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.3.1+0/FFMPEG.v4.3.1.i686-w64-mingw32.tar.gz"
[[FFMPEG]]
arch = "powerpc64le"
git-tree-sha1 = "5e74db92eaf175f9e2fe17a9acfb6a3c08517538"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "bd79824adaae8b2776b199415c67b3763ab22dc151c1da69355751159910ff04"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.3.1+0/FFMPEG.v4.3.1.powerpc64le-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "d60833375f6f4fd2ea16f6522ef1b96926f7c792"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "c711ae85d7a6a9c47f35baa3df38d603c7e2d25d8eab62951f5ff6816d4d96d2"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.3.1+0/FFMPEG.v4.3.1.x86_64-apple-darwin14.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "0b8ee36fe94c508796f536a5304aec7192799148"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "09f81982f6af8b3f139d3699f72dae492ed22f4d1a79dd69e4bee3964311a899"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.3.1+0/FFMPEG.v4.3.1.x86_64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "5a1711c876883821ec1ba1f6ba05c0247ed23a87"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "12bf650b83e6ee191fdbe24ef0609ae326b96f76ae5aa726a196bfd75b5b254d"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.3.1+0/FFMPEG.v4.3.1.x86_64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "36d3ecfa076b46986905f94d4c4a2733acbc012f"
os = "freebsd"

    [[FFMPEG.download]]
    sha256 = "210e0bdad28eb83fb900d8094ddc2e2dc1d4794abbf8dab90176df5a59e8ff02"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.3.1+0/FFMPEG.v4.3.1.x86_64-unknown-freebsd11.1.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "44fc56fb90510aa44c9b5624b706bb13a55210f6"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "1366969e7299f4ab992bfb3ba68c1b96097bbce014b0254ae3749d2202675270"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.3.1+0/FFMPEG.v4.3.1.x86_64-w64-mingw32.tar.gz"
