[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "8e2effd2e099d0cac836faa107b006f2275bdf15"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "521c7f6fc6ff0d52b0d8cf078452b911db91463086fe5b7a71710ad06e88f0f4"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.aarch64-apple-darwin.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "c0eb0ecdb06439cb4d70044684ed754118651bb9"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "89e42bdd6eea60699df42e50c1c42f0776ee8e7340143617e46279b3ece5a60c"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.aarch64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "30b065254a07479adfad85b81d0aa8e655e310dc"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "77f47b97f637694b34b446474012b91a2eae30fef8ad0d84e5be930812a0ce72"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.aarch64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "9bc7c99605dd54b3bbd04eb9496828122c9c94f5"
os = "freebsd"

    [[FFMPEG.download]]
    sha256 = "ae8f2a3bb0e17b7d4253ac6f97a11d731d4c71159998582a24ea715b85e2bd64"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.aarch64-unknown-freebsd.tar.gz"
[[FFMPEG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "52894dfe0d08b5c80ea760b59da07d7a3c6cfb06"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "890cafbe16c631dbc7b46c72e57147445f8b95e89c5bfeaf4ecd5be6632326d1"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.armv6l-linux-gnueabihf.tar.gz"
[[FFMPEG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4e59898087eb52c74de5906f9486a1da6ec1b1cb"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "2cf432044881dd74d7179d579735de72054798e57623b6a9b3e691d99d2a941f"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.armv6l-linux-musleabihf.tar.gz"
[[FFMPEG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "981d496343d43686fcc6e1c35c5d911b5a2c74f8"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "47d795ee8816f9947ee073c99afc5b19ccb86dcc0c6f3923471bdf2b013de771"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.armv7l-linux-gnueabihf.tar.gz"
[[FFMPEG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f46419a434251e38358f61b30ba6f2ee4b86623f"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "c76bb97c7d3044eaffd8c9c31633f78add8621404eae088e2063d4e57caad31a"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.armv7l-linux-musleabihf.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "85b2a6d06df0cc43a2ee8121c606e1d1603c0bde"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "de47029410e61944f9487ffec709bac7c4db00d13dc4adacaccde84bab86e0c9"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.i686-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "47fb885f20ecaf056cfa64d7d4331f16179ef7d9"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "fe7e3dc6eb370e5820c9a39c065273159a1e6cbf8778ad604c5b77cd7bcb4e44"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.i686-linux-musl.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "5b80d8db03e260cc5bb4eaffc5c8d0f29ea70bef"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "db25db26904bdbefb3c73550e18c458a326d4ca774caed7ced947994430495ee"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.i686-w64-mingw32.tar.gz"
[[FFMPEG]]
arch = "powerpc64le"
git-tree-sha1 = "397b47c7b2cd250f6278094cc7f91ff3e44aa61e"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "a06fcf453cb5b96c5f0ad49099d6364e8f66819d88ab342a319afcb4114bdb85"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.powerpc64le-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "riscv64"
git-tree-sha1 = "5cda24fc1fa53fdbd6641ab3debec6e67fa9ddcb"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "5be276bdfee81616d4161af4273c70c718ef8a031b9ccaa80c00cb27cd86bacd"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.riscv64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "7d957ea51284608dcd254f0839df9c3981a5d78c"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "92f0435560ca23eb8f9d0c9293d8cb917def5e71c2d4e7208cfb2394c0e813b1"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.x86_64-apple-darwin.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "d913179b92882e5fc07b4b0b871ada5c5c522627"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "052d458a0193acd203ea134591547a037301cf9469264fd34f22aad440d2583b"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.x86_64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "15c11f01b2714e5d62365a1a7622cc0e9745b80d"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "9f030b765cd73af4f604e4fca48c7a97d3d2c4b8bff951ff81343b22fbbe1bca"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.x86_64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "67b80b05029d2d686ef41e5da7e48ad8d8286154"
os = "freebsd"

    [[FFMPEG.download]]
    sha256 = "ecce1cd9be896b0f263b2896bca9a7c34ed1d032d39de5c82348eeb1e1b9b8da"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.x86_64-unknown-freebsd.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "7a64f03d9f7bd683b3896a81663bdfdb4ee6074c"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "f64901edc0f11ddfcade612451d635cf5749f5ad73b8db1975fc382d1a87a9f2"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v8.0.0+0/FFMPEG.v8.0.0.x86_64-w64-mingw32.tar.gz"
